In [1]:
import numpy as np

In [5]:
#输入数据
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
#标签
Y = np.array([[0,1,1,0]])
#权值初始化，取值范围-1到1
V = np.random.random((3,4))*2-1 
W = np.random.random((4,1))*2-1
print(V)
print(W)
#学习率设置
lr = 0.11

def sigmoid(x):
    return 1/(1 + np.exp(-x))

def dsigmoid(x):
    return x * (1-x)

def update():
    global X,Y,W,V,lr
    
    L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
    L2 = sigmoid(np.dot(L1,W))#隐藏层输出(4,1)
    
    L2_delta = (Y.T -L2)*dsigmoid(L2)
    L1_delta = L2_delta.dot(W.T)*dsigmoid(L1)
    
    W_C = lr * L1.T.dot(L2_delta)
    V_C = lr * X.T.dot(L1_delta)
    
    W = W + W_C
    V = V + V_C

[[-0.08161219  0.97230686  0.28473758  0.75885953]
 [ 0.06862676  0.39984694  0.93030133 -0.80095413]
 [-0.44002617  0.28821373  0.48830348 -0.25373911]]
[[ 0.27293043]
 [-0.18559206]
 [-0.14872268]
 [ 0.87227747]]


In [6]:
for i in range(20000):
    update() #更新权值
    if i % 500 == 0:
        L1 = sigmoid(np.dot(X,V)) #隐藏层输出(4,4)
        L2 = sigmoid(np.dot(L1,W))#隐藏层输出(4,1)
        print('Error:',np.mean(np.abs(Y.T - L2)) )
        
L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
print(L2)

def judge(x):
    if x>=0.5:
        return 1
    else:
        return 0

for i in map(judge,L2):
    print(i)

Error: 0.49997219542737
Error: 0.5000152836089948
Error: 0.4996386593131743
Error: 0.4990999142168367
Error: 0.4976981414643766
Error: 0.49314917916309586
Error: 0.47867329545992343
Error: 0.4419354330559043
Error: 0.3815184089230229
Error: 0.2883477723520345
Error: 0.1943841306004664
Error: 0.1391652576843265
Error: 0.10819569099368231
Error: 0.08922385178572634
Error: 0.07655903425924077
Error: 0.06752180306567998
Error: 0.06074022722691688
Error: 0.05545163854811416
Error: 0.05120155865195466
Error: 0.047703259971391
Error: 0.044767165491233205
Error: 0.042262963730464606
Error: 0.04009811388854096
Error: 0.03820505669774404
Error: 0.03653328876094794
Error: 0.03504427517379711
Error: 0.033708082647829284
Error: 0.032501090796247384
Error: 0.03140439912247993
Error: 0.030402694720397194
Error: 0.029483432208726873
Error: 0.028636229708111513
Error: 0.02785241712419835
Error: 0.027124693636812358
Error: 0.026446864706810503
Error: 0.02581363780314881
Error: 0.025220462054732162
Error